# Site settings
title: superkhau.com
email: superkhau@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  l33t only.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://superkhau.com" # the base hostname & protocol for your site
twitter_username: superkhau_
github_username:  superkhau

# Build settings
markdown: kramdown
